### ISSUE TITLE
User Story 1: User Authentication and Gallery Access

### ISSUE THREAD

**Issue by ak-coding-ber** [ak-coding-ber/capstone-andreask-retrogram#1]
### Value Proposition

As a user,  
I want to log into the website,  
So that I can access the gallery and other interactive features like comments, likes, and generating pixel art.

### Description

- Users can log in using an email and password or oauth-functionality.
- Users can sign up for an account if they don't already have one.
- After logging in, users gain access to the gallery and other features such as commenting, liking, and generating pixel art.

### Acceptance Criteria

- [x] Users can sign up with via github or google.
- [x] Users can log in with valid credentials.
- [x] A "Log Out" button should be visible when logged in.
- [x] User Info gets stored in the Database

### Tasks

- [x] #4
- [x] #3
- [x] #5
- [x]  implement mongo db adapter
