### ISSUE TITLE
User Story 7: Guest View

### ISSUE THREAD

**Issue by ak-coding-ber** [ak-coding-ber/capstone-andreask-retrogram#27]
### Value Proposition

As a Guest (not logged in) I want to see the core feature of Retrogram (switch to retro mode) and get a visual impression of the UI.
I want to get an idea what kind of images other users create and see the creations with the highest amount of likes.

### Description

- Guests can see the gallery page, the details page and the comments
- Guests can switch between retro mode and normal mode
- Guests can see all photos marked as public
- Guests will see the creations first, that have the most likes

### Acceptance Criteria

- [ ] Gallery page is shown to guests without like button and erase button 
- [ ] Guests only see photos marked as public
- [ ] public fotos are sorted by amount of likes in descending order

### Tasks

- [ ] implement function: mark as public
- [ ] create new guest page without erase and like function 
- [ ] Sort pictures by amount of likes (descending)
- [ ] remove upload tab on guest page
