### ISSUE TITLE
User Story 3: Toggle Between Normal and Pixel-Art Versions

### ISSUE THREAD

**Issue by ak-coding-ber** [ak-coding-ber/capstone-andreask-retrogram#6]
### Value Proposition

As a user,  
I want to switch between the normal and retro (pixel-art) versions of photos,  
So that I can view both the original and retro versions of each image.

### Description

- Each photo will have a pixel-art version pre-uploaded along with the original.
- A button will allow users to toggle between the normal version and the pixel-art version of the photo.

### Acceptance Criteria

- [x] A "Toggle Pixel-Art" button is available gallery page.
- [x] A "Toggle Pixel-Art" button is available for each photo on the detailed foto page.
- [x] Clicking the button switches the displayed photo between its normal and pixel-art version.

### Tasks

- [x] Pre-upload pixel-art versions of photos along with the original.
- [x] Implement button on gallery page that toggles between the normal and pixel-art version
- [x] Implement button on details page that toggles between the normal and pixel-art version
- [x] isRetro State should be preserved across all pages
