### ISSUE TITLE
User Story 6: File Upload Functionality

### ISSUE THREAD

**Issue by ak-coding-ber** [ak-coding-ber/capstone-andreask-retrogram#9]
### Value Proposition

As a logged-in user,  
I want to upload new photos to the gallery with both normal and retro (pixel-art) versions,  
So that I can contribute my own content in both formats.

### Description

- Logged-in users can upload new photos to the gallery.
- The user uploads both the original and pixel-art versions of the photo.
- A description is required for the uploaded photos.

### Acceptance Criteria

- [ ] Users have to upload both the normal and retro versions of the photo.
- [ ] A description is required generate and upload the retro version
- [ ] If the user doesn't like the generated picture it can be re-generated
- [ ] The photo appears in the gallery once uploaded
- [ ] Users can toggle between normal and pixel-art versions of the uploaded photo.

### Tasks

- [ ] Create the photo upload form for logged-in users with fields for both normal and retro versions.
- [ ] Implement the functionality to store the uploaded photos and description.
- [ ] Ensure the uploaded photos appear in the gallery with a toggle functionality.
